apiVersion: 1

# This a list of predefined datasources. With it the Grafana container start instantly with some
# data connections to query from. For a list of all possible settings:
# https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    isDefault: true
    editable: true

# To check out the functioning Grafana installation open http://localhost:3000/ and use `admin:admin` to login.
# There should be now the datasource already configured as well as a dashboard.
