server:
  disable: true

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: monitoring_cats
    static_configs:
      - labels:
          job: monitoring_cats
          __path__: /logmount/cat.log
  - job_name: system
    static_configs:
      - labels:
          job: system
          __path__: /var/log/*log

