{
 "title": "Glances",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Latest Metrics",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "glances_cpu_total", "legendFormat": "CPU (all)" },
    { "expr": "glances_mem_percent", "legendFormat": "Memory" }
   ]
  },
  {
   "title": "CPUs",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "glances_percpu_0_total", "legendFormat": "CPU 0" },
    { "expr": "glances_percpu_1_total", "legendFormat": "CPU 1" },
    { "expr": "glances_percpu_2_total", "legendFormat": "CPU 2" },
    { "expr": "glances_percpu_3_total", "legendFormat": "CPU 3" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "glances_mem_used", "legendFormat": "Used" },
    { "expr": "glances_mem_active", "legendFormat": "Active" },
    { "expr": "glances_memswap_used", "legendFormat": "Swap Used" }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "glances_diskio_sda_read_bytes", "legendFormat": "Read" },
    { "expr": "glances_diskio_sda_write_bytes", "legendFormat": "Write" }
   ]
  },
  {
   "title": "System Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "glances_uptime_seconds", "legendFormat": "System uptime" }
   ]
  },
  {
   "title": "Docker CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glances_docker_infrastructure_glances_1_cpu_percent",
     "legendFormat": "Glances"
    },
    {
     "expr": "glances_docker_infrastructure_grafana_1_cpu_percent",
     "legendFormat": "Grafana"
    },
    {
     "expr": "glances_docker_infrastructure_prometheus_1_cpu_percent",
     "legendFormat": "Prometheus"
    }
   ]
  },
  {
   "title": "Processes / Threads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "glances_processcount_total", "legendFormat": "Total processes" },
    { "expr": "glances_processcount_running", "legendFormat": "Running processes" },
    { "expr": "glances_processcount_thread", "legendFormat": "Total threads" }
   ]
  },
  {
   "title": "System Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{filename=\"/var/log/syslog\",job=\"system\"}"
    }
   ]
  }
 ]
}