{
 "title": "Simple Spring Boot",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Loglines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(logback_events_total[1m])", "legendFormat": "{{level}}" }
   ]
  },
  {
   "title": "JVM Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "files" } },
   "yaxes": [
    { "format": "files" }
   ],
   "targets": [
    { "expr": "process_files_open_files", "legendFormat": "Open Files" }
   ]
  },
  {
   "title": "JVM GC Allocated",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_memory_allocated_bytes_total",
     "legendFormat": "Allocated Bytes"
    }
   ]
  },
  {
   "title": "Active Tomcat Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tomcat_sessions_active_current_sessions"
    }
   ]
  },
  {
   "title": "Server Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_uptime_seconds" }
   ]
  },
  {
   "title": "Successful Requests on Endpoints",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 8, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "requests" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_server_requests_seconds_count{status=\"200\"}",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}